name: learn-github-actions
on:
  label:
    types:
      - created
  issues:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test steps 1
        run: echo "This is Test STEPS 1!"

  job_name_test:
    runs-on: ubuntu-latest
    steps:
      - name: steps name 1
        run: echo "This is job_name_test!"
      - name: steps name 2
        run: ls -al